### ISSUE TITLE
gactions test error.

### ISSUE THREAD

**Issue by GAZ082** [i8beef/HomeAutio.Mqtt.Core#3]
Hey. Just came from honeymoon after having all my devices unplugged. Started server, updated the docker image and everything seemed to work but when shout a command GA said there was a problem.

Tried the ./gactions test --action_package action.json --project  asistente-xxx --preview_mins 9999999 thing again and failed:

```
./gactions test --action_package action.json --project  asistente-de8b4 --preview_mins 9999999
Pushing the app for the Assistant for testing...
ERROR: Failed to test the app for the Assistant
ERROR: Internal error encountered.
```
The login page works fine, but cant find the service in the list of vendors in the Google Home app.

Thanks!

**Comment by i8beef** [comment]
Can you open this over here instead so we can share the response with anyone else with the issue?

https://github.com/i8beef/HomeAutio.Mqtt.GoogleHome/issues

**Comment by GAZ082** [comment]
Oh sure! Did not realize this was not the correct repo! Thanks!
